### ISSUE TITLE
Feature Request: Maximum interval when using `backoffFactor`

### ISSUE THREAD

**Issue by adamhamlin** [AlonMiz/poll-until-promise#22]
Hi,

Would you accept a PR for a new option like `maxBackoffInterval`? For example, if you specified `interval` = 1, `backoffFactor` = 2, and `maxBackoffInterval` = 10, you'll get retries at 1, 2, 4, 8, 10, 10, 10, 10, 10, ... and so on until success or timeout reached.

Backoff retry is obviously great but growing without bound is probably not wanted in practice.

Thanks!

**Comment by AlonMiz** [comment]
i agree, that's a good ability. we should also think of a good default
something like `backoffFactor**5`

**Comment by adamhamlin** [comment]
Sure, I could put in a default if you'd like. Could be considered a breaking change tho unless it's an opt-in feature

**Comment by AlonMiz** [comment]
done as part of https://github.com/AlonMiz/poll-until-promise/pull/24
