### ISSUE TITLE
Using `backoffFactor` will affect the first retry interval

### ISSUE THREAD

**Issue by adamhamlin** [AlonMiz/poll-until-promise#23]
For example, if you use `backoffFactor` = 2 and `interval` = 1000, the first retry will take place after 2000ms. I would expect the first retry to take place after 1000ms and the second retry to take place after 2000ms.

If that is intentional, a usage note in the docs would be nice.

**Comment by AlonMiz** [comment]
done as part of https://github.com/AlonMiz/poll-until-promise/pull/24
