### ISSUE TITLE
if u throw an error from inside of waitFor function it doesn't print the full stack-trace

### ISSUE THREAD

**Issue by Madvinking** [AlonMiz/poll-until-promise#5]
```
const { waitFor } = require('poll-until-promise');
function A() {
return waitFor(() => {
  if (Math.random() >= 0.5) {
    throw new Error('try again');
  } else {
    console.log('all good')
  }
})
}

async function B() {
 await A()
}
```
this will not give stacktrace of B

**Comment by AlonMiz** [comment]
It would be great if you can contribute a fix.

**Comment by AlonMiz** [comment]
basically, it does show the stacktrace including B and A,
but in case there was another interaction it will only show the `try again` message.
i guess we can somehow combine the original execution stacktrace with the latest failure...
a bit tricky but might work

**Comment by AlonMiz** [comment]
merged a solution for that case, as setTimeout will not store the stacktrace of the whole flow in case of failure.
so i just combined the original stacktrace and the last stack together.
